---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    ignore-check.kube-linter.io/no-anti-affinity: "This deployment runs on a single node"
    ignore-check.kube-linter.io/run-as-non-root: "This deployment needs to run as privileged because it uses http port"
    ignore-check.kube-linter.io/no-read-only-root-fs: "This deployment needs to write on root fsr to write nginx log"
  name: nginx-deployment
  namespace: mon-test
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.27-alpine
          name: nginx
          ports:
            - containerPort: 80
          # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m" # 0.25
            limits:
              memory: "128Mi"
              cpu: "500m"  # 0.5
          # https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
          securityContext: {}
            # readOnlyRootFilesystem: true
            # runAsNonRoot: true
